Description: Creates root S3 buckets

Mappings:
  RegionMap:
    us-east-1:
      S3hostedzoneID: Z3AQBSTGFYJSTF
      websiteendpoint: s3-website-us-east-1.amazonaws.com
    us-west-1:
      S3hostedzoneID: Z2F56UZL2M1ACD
      websiteendpoint: s3-website-us-west-1.amazonaws.com
    us-west-2:
      S3hostedzoneID: Z3BJ6K6RIION7M
      websiteendpoint: s3-website-us-west-2.amazonaws.com
    eu-west-1:
      S3hostedzoneID: Z1BKCTXD74EZPE
      websiteendpoint: s3-website-eu-west-1.amazonaws.com
    ap-southeast-1:
      S3hostedzoneID: Z3O0J2DXBE1FTB
      websiteendpoint: s3-website-ap-southeast-1.amazonaws.com
    ap-southeast-2:
      S3hostedzoneID: Z1WCIGYICN2BYD
      websiteendpoint: s3-website-ap-southeast-2.amazonaws.com
    ap-northeast-1:
      S3hostedzoneID: Z2M4EHUR26P7ZW
      websiteendpoint: s3-website-ap-northeast-1.amazonaws.com
    sa-east-1:
      S3hostedzoneID: Z31GFT0UA1I2HV
      websiteendpoint: s3-website-sa-east-1.amazonaws.com
Resources:
  RootBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', ["websites", !Ref "AWS::AccountId"]]
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', ["logs", !Ref "AWS::AccountId"]]
      AccessControl: LogDeliveryWrite
  TemplateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', ["templates", !Ref "AWS::AccountId"]]
      AccessControl: BucketOwnerFullControl
Outputs:
  WebsiteBucketUrl:
    Value: !GetAtt RootBucket.WebsiteURL
    Description: URL for website hosted on S3
    Export: 
      Name: WebsiteBucketUrl
  LogBucketArn:
    Value: !GetAtt LogBucket.Arn
    Description: Log bucket ARN
    Export: 
      Name: LogBucketArn
  TemplateBucketArn:
    Value: !GetAtt TemplateBucket.Arn
    Description: Template bucket ARN
    Export: 
      Name: TemplateBucketArn